export const FRAUD_CONSTANTS = {

    VELOCITY: {

        MAX_TRANSACTIONS_PER_MINUTE: 5,

        MAX_TRANSACTIONS_PER_HOUR: 20,

        MAX_AMOUNT_PER_HOUR: 10_000_000,

        MAX_AMOUNT_PER_DAY: 50_000_000,

    },

    RISK_SCORE: {

        VELOCITY_1M: 30,

        VELOCITY_1H: 20,

        AMOUNT_1H: 25,

        AMOUNT_24H: 25,

        MAX: 100,

    },

    ANOMALY: {
        AMOUNT_MULTIPLIER:5,
        TRANSACTION_COUNT_MULTIPLIER:3,
        LARGE_AMOUNT_TRESHOLD: 25_000_000,
        AMOUNT_RISK_SCORE: 30,
        FREQUENCY_RISK_SCORE: 25,
        LARGE_AMOUNT_RISK_SCORE: 20,
    },

    RISK_LEVEL: {
        LOW_MAX: 24,
        MEDIUM_MAX: 49,
        HIGH_MAX: 74,
        CRITICAL_MAX: 100,
    },

    DEVICE: {
         MAX_DEVICES_PER_USER: 5,
        MAX_DEVICE_TRANSACTIONS_24H: 100,
        NEW_DEVICE_RISK_SCORE: 15,
        HIGH_DEVICE_ACTIVITY_RISK_SCORE: 30,
        TOO_MANY_DEVICES_RISK_SCORE: 25,
    },

    GEOLOCATION: {
        MAX_TRAVEL_SPEED_KMH: 900,
        SUSPICIOUS_DISTANCE_KM: 500,
        TRUSTED_LOCATION_RADIUS_KM: 5,
        DISTANCE_RISK_SCORE: 20,
        IMPOSSIBLE_TRAVEL_RISK_SCORE: 50,
        UNTRUSTED_LOCATION_RISK_SCORE: 15
    },

    SUSPICIOUS_ACTIVITY: {
    TRANSACTION_COUNT_1M_THRESHOLD: 5,
    TRANSACTION_COUNT_1H_THRESHOLD: 20,
    FAILED_TRANSACTION_1H_THRESHOLD: 5,
    AMOUNT_SPIKE_MULTIPLIER: 5,
    INACTIVE_PERIOD_HOURS: 72,
    VELOCITY_RISK_SCORE: 25,
    HIGH_VELOCITY_RISK_SCORE: 35,
    FAILED_TRANSACTION_RISK_SCORE: 20,
    AMOUNT_SPIKE_RISK_SCORE: 25,
    DORMANT_ACCOUNT_RISK_SCORE: 15,
},

} as const;