export const NOTIFICATION_TYPE = {
    TRANSFER_SUCCESS: "TRANSFER_SUCCESS",
    TRANSFER_FAILED: "TRANSFER_FAILED",

    PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
    PAYMENT_FAILED: "PAYMENT_FAILED",

    WITHDRAWAL_CREATED: "WITHDRAWAL_CREATED",
    WITHDRAWAL_PROCESSING: "WITHDRAWAL_PROCESSING",
    WITHDRAWAL_SUCCESS: "WITHDRAWAL_SUCCESS",
    WITHDRAWAL_FAILED: "WITHDRAWAL_FAILED",

    FRAUD_ALERT: "FRAUD_ALERT",

    SECURITY_ALERT: "SECURITY_ALERT",
} as const;

export type NotificationType =
    typeof NOTIFICATION_TYPE[
        keyof typeof NOTIFICATION_TYPE
    ];